// 서울 대장아파트 22개 (BlueChipTrends.js에서 추출)

export const BLUE_CHIP_APARTMENTS = [
  { name: '래미안원베일리', regionId: '11650', dong: '반포동', district: '서초구 반포동' },
  { name: '트리마제', regionId: '11200', dong: '성수동', district: '성동구 성수동' },
  { name: '래미안대치팰리스', regionId: '11680', dong: '대치동', district: '강남구 대치동' },
  { name: '잠실래미안아이파크', regionId: '11710', dong: '잠실동', district: '송파구 잠실동' },
  { name: '리센츠', regionId: '11710', dong: '잠실동', district: '송파구 잠실동' },
  { name: '시범', regionId: '11560', dong: '여의도동', district: '영등포구 여의도동' },
  { name: '방배그랑자이', regionId: '11650', dong: '방배동', district: '서초구 방배동' },
  { name: '올림픽파크포레온', regionId: '11740', dong: '둔촌동', district: '강동구 둔촌동' },
  { name: '래미안옥수리버젠', regionId: '11200', dong: '옥수동', district: '성동구 옥수동' },
  { name: '마포프레스티지자이', regionId: '11440', dong: '아현동', district: '마포구 아현동' },
  { name: '아크로리버하임', regionId: '11590', dong: '흑석동', district: '동작구 흑석동' },
  { name: '경희궁자이', regionId: '11110', dong: '홍파동', district: '종로구 홍파동' },
  { name: '서울숲리버뷰자이', regionId: '11200', dong: '행당동', district: '성동구 행당동' },
  { name: '고덕그라시움', regionId: '11740', dong: '고덕동', district: '강동구 고덕동' },
  { name: '광장힐스테이트', regionId: '11215', dong: '광장동', district: '광진구 광장동' },
  { name: '센트라스', regionId: '11200', dong: '하왕십리동', district: '성동구 하왕십리동' },
  { name: '롯데캐슬리버파크시그니처', regionId: '11215', dong: '자양동', district: '광진구 자양동' },
  { name: '목동힐스테이트', regionId: '11470', dong: '신정동', district: '양천구 신정동' },
  { name: 'e편한세상상도노빌리티', regionId: '11590', dong: '상도동', district: '동작구 상도동' },
  { name: '래미안위례', regionId: '11710', dong: '장지동', district: '송파구 장지동' },
  { name: '마곡엠밸리7단지', regionId: '11500', dong: '마곡동', district: '강서구 마곡동' },
  { name: '보라매SK뷰', regionId: '11560', dong: '신길동', district: '영등포구 신길동' },
];
