// 수도권 지역코드 (LAWD_CD 5자리)
// 서울 25구 + 경기 주요 시/구 + 인천 주요 구

export const REGIONS = [
  // ── 서울 (25구) ──
  { id: "11110", name: "종로구", city: "서울", fullLabel: "서울 종로구", tier: 3 },
  { id: "11140", name: "중구", city: "서울", fullLabel: "서울 중구", tier: 3 },
  { id: "11170", name: "용산구", city: "서울", fullLabel: "서울 용산구", tier: 2 },
  { id: "11200", name: "성동구", city: "서울", fullLabel: "서울 성동구", tier: 2 },
  { id: "11215", name: "광진구", city: "서울", fullLabel: "서울 광진구", tier: 3 },
  { id: "11230", name: "동대문구", city: "서울", fullLabel: "서울 동대문구", tier: 3 },
  { id: "11260", name: "중랑구", city: "서울", fullLabel: "서울 중랑구", tier: 4 },
  { id: "11290", name: "성북구", city: "서울", fullLabel: "서울 성북구", tier: 3 },
  { id: "11305", name: "강북구", city: "서울", fullLabel: "서울 강북구", tier: 4 },
  { id: "11320", name: "도봉구", city: "서울", fullLabel: "서울 도봉구", tier: 4 },
  { id: "11350", name: "노원구", city: "서울", fullLabel: "서울 노원구", tier: 4 },
  { id: "11380", name: "은평구", city: "서울", fullLabel: "서울 은평구", tier: 3 },
  { id: "11410", name: "서대문구", city: "서울", fullLabel: "서울 서대문구", tier: 3 },
  { id: "11440", name: "마포구", city: "서울", fullLabel: "서울 마포구", tier: 2 },
  { id: "11470", name: "양천구", city: "서울", fullLabel: "서울 양천구", tier: 3 },
  { id: "11500", name: "강서구", city: "서울", fullLabel: "서울 강서구", tier: 3 },
  { id: "11530", name: "구로구", city: "서울", fullLabel: "서울 구로구", tier: 4 },
  { id: "11545", name: "금천구", city: "서울", fullLabel: "서울 금천구", tier: 4 },
  { id: "11560", name: "영등포구", city: "서울", fullLabel: "서울 영등포구", tier: 2 },
  { id: "11590", name: "동작구", city: "서울", fullLabel: "서울 동작구", tier: 3 },
  { id: "11620", name: "관악구", city: "서울", fullLabel: "서울 관악구", tier: 4 },
  { id: "11650", name: "서초구", city: "서울", fullLabel: "서울 서초구", tier: 1 },
  { id: "11680", name: "강남구", city: "서울", fullLabel: "서울 강남구", tier: 1 },
  { id: "11710", name: "송파구", city: "서울", fullLabel: "서울 송파구", tier: 1 },
  { id: "11740", name: "강동구", city: "서울", fullLabel: "서울 강동구", tier: 2 },

  // ── 경기 (주요 시/구) ──
  { id: "41111", name: "수원장안구", city: "경기", fullLabel: "경기 수원장안구", tier: 3 },
  { id: "41113", name: "수원권선구", city: "경기", fullLabel: "경기 수원권선구", tier: 3 },
  { id: "41115", name: "수원팔달구", city: "경기", fullLabel: "경기 수원팔달구", tier: 3 },
  { id: "41117", name: "수원영통구", city: "경기", fullLabel: "경기 수원영통구", tier: 2 },
  { id: "41131", name: "성남수정구", city: "경기", fullLabel: "경기 성남수정구", tier: 3 },
  { id: "41133", name: "성남중원구", city: "경기", fullLabel: "경기 성남중원구", tier: 3 },
  { id: "41135", name: "성남분당구", city: "경기", fullLabel: "경기 성남분당구", tier: 1 },
  { id: "41150", name: "의정부시", city: "경기", fullLabel: "경기 의정부시", tier: 4 },
  { id: "41170", name: "안양만안구", city: "경기", fullLabel: "경기 안양만안구", tier: 3 },
  { id: "41173", name: "안양동안구", city: "경기", fullLabel: "경기 안양동안구", tier: 2 },
  { id: "41190", name: "부천시", city: "경기", fullLabel: "경기 부천시", tier: 3 },
  { id: "41210", name: "광명시", city: "경기", fullLabel: "경기 광명시", tier: 2 },
  { id: "41220", name: "평택시", city: "경기", fullLabel: "경기 평택시", tier: 4 },
  { id: "41250", name: "동두천시", city: "경기", fullLabel: "경기 동두천시", tier: 4 },
  { id: "41270", name: "안산상록구", city: "경기", fullLabel: "경기 안산상록구", tier: 4 },
  { id: "41273", name: "안산단원구", city: "경기", fullLabel: "경기 안산단원구", tier: 4 },
  { id: "41280", name: "고양덕양구", city: "경기", fullLabel: "경기 고양덕양구", tier: 3 },
  { id: "41285", name: "고양일산동구", city: "경기", fullLabel: "경기 고양일산동구", tier: 2 },
  { id: "41287", name: "고양일산서구", city: "경기", fullLabel: "경기 고양일산서구", tier: 3 },
  { id: "41290", name: "과천시", city: "경기", fullLabel: "경기 과천시", tier: 1 },
  { id: "41310", name: "구리시", city: "경기", fullLabel: "경기 구리시", tier: 3 },
  { id: "41360", name: "남양주시", city: "경기", fullLabel: "경기 남양주시", tier: 3 },
  { id: "41370", name: "오산시", city: "경기", fullLabel: "경기 오산시", tier: 4 },
  { id: "41390", name: "시흥시", city: "경기", fullLabel: "경기 시흥시", tier: 4 },
  { id: "41410", name: "군포시", city: "경기", fullLabel: "경기 군포시", tier: 3 },
  { id: "41430", name: "의왕시", city: "경기", fullLabel: "경기 의왕시", tier: 3 },
  { id: "41450", name: "하남시", city: "경기", fullLabel: "경기 하남시", tier: 2 },
  { id: "41460", name: "용인처인구", city: "경기", fullLabel: "경기 용인처인구", tier: 4 },
  { id: "41463", name: "용인기흥구", city: "경기", fullLabel: "경기 용인기흥구", tier: 3 },
  { id: "41465", name: "용인수지구", city: "경기", fullLabel: "경기 용인수지구", tier: 2 },
  { id: "41480", name: "파주시", city: "경기", fullLabel: "경기 파주시", tier: 4 },
  { id: "41500", name: "이천시", city: "경기", fullLabel: "경기 이천시", tier: 4 },
  { id: "41550", name: "김포시", city: "경기", fullLabel: "경기 김포시", tier: 3 },
  { id: "41570", name: "화성시", city: "경기", fullLabel: "경기 화성시", tier: 3 },
  { id: "41590", name: "광주시", city: "경기", fullLabel: "경기 광주시", tier: 3 },

  // ── 인천 (주요 구/군) ──
  { id: "28110", name: "중구", city: "인천", fullLabel: "인천 중구", tier: 4 },
  { id: "28140", name: "동구", city: "인천", fullLabel: "인천 동구", tier: 4 },
  { id: "28177", name: "미추홀구", city: "인천", fullLabel: "인천 미추홀구", tier: 3 },
  { id: "28185", name: "연수구", city: "인천", fullLabel: "인천 연수구", tier: 2 },
  { id: "28200", name: "남동구", city: "인천", fullLabel: "인천 남동구", tier: 3 },
  { id: "28237", name: "부평구", city: "인천", fullLabel: "인천 부평구", tier: 3 },
  { id: "28245", name: "계양구", city: "인천", fullLabel: "인천 계양구", tier: 3 },
  { id: "28260", name: "서구", city: "인천", fullLabel: "인천 서구", tier: 3 },
  { id: "28710", name: "강화군", city: "인천", fullLabel: "인천 강화군", tier: 4 },
  { id: "28720", name: "옹진군", city: "인천", fullLabel: "인천 옹진군", tier: 4 },
];

export const SEOUL_REGIONS = REGIONS.filter(r => r.city === "서울");
export const GYEONGGI_REGIONS = REGIONS.filter(r => r.city === "경기");
export const INCHEON_REGIONS = REGIONS.filter(r => r.city === "인천");
